Repository CA-G12/eBooks-2, pull requests merged in 2022-08, with the labels that each got.

#2 added the file structure & the data to the books.json file
  .gitignore
  index.html
  package-lock.json
  package.json
  public/HomePage/home.css
  public/HomePage/home.html
  public/HomePage/script.js
  public/LandingPage/styles.css
  src/books.json
  src/router.js
  src/server.js
  tests/.eslintrc.json
  tests/pureFunctions.test.js
Labels: approved

#5 Created readme file
  README.md
Labels: awaiting review, approved

#7 Create landing page
  .eslintrc.json
  index.html
  public/LandingPage/styles.css
  public/imgs/landing.png
Labels: approved

#8 6 create books page
  public/HomePage/home.css
  public/HomePage/home.html
Labels: approved

#14 Autocomplete search
  public/HomePage/fetch.js
  public/HomePage/home.css
  public/HomePage/home.html
  public/HomePage/script.js
  public/LandingPage/styles.css
Labels: approved

#16 15 books dom
  public/HomePage/home.css
  public/HomePage/script.js
Labels: awaiting review

#20 19 get selected book
  public/HomePage/script.js
Labels: awaiting review

#22 edit search input and list css
  public/HomePage/home.css
Labels: awaiting review

#29 Add tests
  src/handlers/notfoundHandler.js
  tests/pureFunctions.test.js
Labels: approved

#30 procfile
  procfile
Labels: approved

#34 added index.js file in handlers and removed imported modules from the…
  src/handlers/index.js
  src/router.js
Labels: approved

#35 edit live link
  README.md
Labels: approved

#36 font edit
  public/LandingPage/styles.css
Labels: approved
